# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  # Do not build branches
  branches:
    exclude:
      - "*"
  # Run build on tagged versions
  tags:
    include:
      - "v*"

# Run builds for PRs against `master`
pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

container: golang:1.13

steps:

- script: |
    apt-get update && apt-get install zip -y
    go version
    go get -v -t -d ./...
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi
  displayName: 'Get dependencies'



- script: |
    # etcd depdendency bug workaround. See commends in go.mod for more details.
    go build -v . && rm /go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go
    go test -v ./...
  displayName: 'Run tests'

- script: |
    mkdir dist && cd dist
    env GOOS=windows GOARCH=amd64 go build -v -o ./dce ..
    zip -m dce_windows_amd64.zip ./dce
    env GOOS=linux GOARCH=amd64 go build -v -o ./dce ..
    zip -m dce_linux_amd64.zip ./dce
    env GOOS=darwin GOARCH=amd64 go build -v -o ./dce ..
    zip -m dce_darwin_amd64.zip ./dce
  displayName: 'Build and zip'

# Publish a Github Release for tagged commits
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops
- task: GithubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
    action: create
    tagSource: 'User specified tag'
    gitHubConnection: Github
    repositoryName: Optum/dce-cli
    isDraft: true
    assets: |
      ./dist/*