// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Accounter is an autogenerated mock type for the Accounter type
type Accounter struct {
	mock.Mock
}

// AddAccount provides a mock function with given fields: accountID, adminRoleARN
func (_m *Accounter) AddAccount(accountID string, adminRoleARN string) {
	_m.Called(accountID, adminRoleARN)
}

// GetAccount provides a mock function with given fields: accountID
func (_m *Accounter) GetAccount(accountID string) {
	_m.Called(accountID)
}

// ListAccounts provides a mock function with given fields:
func (_m *Accounter) ListAccounts() {
	_m.Called()
}

// RemoveAccount provides a mock function with given fields: accountID
func (_m *Accounter) RemoveAccount(accountID string) {
	_m.Called(accountID)
}
