// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import operations "github.com/Optum/dce-cli/client/operations"
import util "github.com/Optum/dce-cli/internal/util"

// APIer is an autogenerated mock type for the APIer type
type APIer struct {
	mock.Mock
}

// InitApiClient provides a mock function with given fields:
func (_m *APIer) InitApiClient() *operations.Client {
	ret := _m.Called()

	var r0 *operations.Client
	if rf, ok := ret.Get(0).(func() *operations.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.Client)
		}
	}

	return r0
}

// Request provides a mock function with given fields: input
func (_m *APIer) Request(input *util.ApiRequestInput) *util.ApiResponse {
	ret := _m.Called(input)

	var r0 *util.ApiResponse
	if rf, ok := ret.Get(0).(func(*util.ApiRequestInput) *util.ApiResponse); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*util.ApiResponse)
		}
	}

	return r0
}
