// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import operations "github.com/Optum/dce-cli/client/operations"
import runtime "github.com/go-openapi/runtime"

// APIer is an autogenerated mock type for the APIer type
type APIer struct {
	mock.Mock
}

// DeleteAccountsID provides a mock function with given fields: _a0, _a1
func (_m *APIer) DeleteAccountsID(_a0 *operations.DeleteAccountsIDParams, _a1 runtime.ClientAuthInfoWriter) (*operations.DeleteAccountsIDNoContent, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.DeleteAccountsIDNoContent
	if rf, ok := ret.Get(0).(func(*operations.DeleteAccountsIDParams, runtime.ClientAuthInfoWriter) *operations.DeleteAccountsIDNoContent); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeleteAccountsIDNoContent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.DeleteAccountsIDParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLeases provides a mock function with given fields: _a0, _a1
func (_m *APIer) DeleteLeases(_a0 *operations.DeleteLeasesParams, _a1 runtime.ClientAuthInfoWriter) (*operations.DeleteLeasesCreated, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.DeleteLeasesCreated
	if rf, ok := ret.Get(0).(func(*operations.DeleteLeasesParams, runtime.ClientAuthInfoWriter) *operations.DeleteLeasesCreated); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeleteLeasesCreated)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.DeleteLeasesParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccounts provides a mock function with given fields: _a0, _a1
func (_m *APIer) GetAccounts(_a0 *operations.GetAccountsParams, _a1 runtime.ClientAuthInfoWriter) (*operations.GetAccountsOK, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.GetAccountsOK
	if rf, ok := ret.Get(0).(func(*operations.GetAccountsParams, runtime.ClientAuthInfoWriter) *operations.GetAccountsOK); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetAccountsOK)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.GetAccountsParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountsID provides a mock function with given fields: _a0, _a1
func (_m *APIer) GetAccountsID(_a0 *operations.GetAccountsIDParams, _a1 runtime.ClientAuthInfoWriter) (*operations.GetAccountsIDOK, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.GetAccountsIDOK
	if rf, ok := ret.Get(0).(func(*operations.GetAccountsIDParams, runtime.ClientAuthInfoWriter) *operations.GetAccountsIDOK); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetAccountsIDOK)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.GetAccountsIDParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeases provides a mock function with given fields: _a0, _a1
func (_m *APIer) GetLeases(_a0 *operations.GetLeasesParams, _a1 runtime.ClientAuthInfoWriter) (*operations.GetLeasesOK, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.GetLeasesOK
	if rf, ok := ret.Get(0).(func(*operations.GetLeasesParams, runtime.ClientAuthInfoWriter) *operations.GetLeasesOK); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetLeasesOK)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.GetLeasesParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeasesID provides a mock function with given fields: _a0, _a1
func (_m *APIer) GetLeasesID(_a0 *operations.GetLeasesIDParams, _a1 runtime.ClientAuthInfoWriter) (*operations.GetLeasesIDOK, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.GetLeasesIDOK
	if rf, ok := ret.Get(0).(func(*operations.GetLeasesIDParams, runtime.ClientAuthInfoWriter) *operations.GetLeasesIDOK); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetLeasesIDOK)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.GetLeasesIDParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsage provides a mock function with given fields: _a0, _a1
func (_m *APIer) GetUsage(_a0 *operations.GetUsageParams, _a1 runtime.ClientAuthInfoWriter) (*operations.GetUsageOK, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.GetUsageOK
	if rf, ok := ret.Get(0).(func(*operations.GetUsageParams, runtime.ClientAuthInfoWriter) *operations.GetUsageOK); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetUsageOK)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.GetUsageParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostAccounts provides a mock function with given fields: _a0, _a1
func (_m *APIer) PostAccounts(_a0 *operations.PostAccountsParams, _a1 runtime.ClientAuthInfoWriter) (*operations.PostAccountsCreated, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.PostAccountsCreated
	if rf, ok := ret.Get(0).(func(*operations.PostAccountsParams, runtime.ClientAuthInfoWriter) *operations.PostAccountsCreated); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.PostAccountsCreated)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.PostAccountsParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostLeases provides a mock function with given fields: _a0, _a1
func (_m *APIer) PostLeases(_a0 *operations.PostLeasesParams, _a1 runtime.ClientAuthInfoWriter) (*operations.PostLeasesCreated, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.PostLeasesCreated
	if rf, ok := ret.Get(0).(func(*operations.PostLeasesParams, runtime.ClientAuthInfoWriter) *operations.PostLeasesCreated); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.PostLeasesCreated)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.PostLeasesParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostLeasesIDAuth provides a mock function with given fields: _a0, _a1
func (_m *APIer) PostLeasesIDAuth(_a0 *operations.PostLeasesIDAuthParams, _a1 runtime.ClientAuthInfoWriter) (*operations.PostLeasesIDAuthCreated, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *operations.PostLeasesIDAuthCreated
	if rf, ok := ret.Get(0).(func(*operations.PostLeasesIDAuthParams, runtime.ClientAuthInfoWriter) *operations.PostLeasesIDAuthCreated); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.PostLeasesIDAuthCreated)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.PostLeasesIDAuthParams, runtime.ClientAuthInfoWriter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetTransport provides a mock function with given fields: _a0
func (_m *APIer) SetTransport(_a0 runtime.ClientTransport) {
	_m.Called(_a0)
}
