// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Authenticater is an autogenerated mock type for the Authenticater type
type Authenticater struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: authUrl
func (_m *Authenticater) Authenticate(authUrl string) {
	_m.Called(authUrl)
}
