// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Authenticater is an autogenerated mock type for the Authenticater type
type Authenticater struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields:
func (_m *Authenticater) Authenticate() {
	_m.Called()
}
