// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AWSer is an autogenerated mock type for the AWSer type
type AWSer struct {
	mock.Mock
}

// UpdateLambdasFromS3Assets provides a mock function with given fields: lambdaNames, bucket, namespace
func (_m *AWSer) UpdateLambdasFromS3Assets(lambdaNames []string, bucket string, namespace string) {
	_m.Called(lambdaNames, bucket, namespace)
}

// UploadDirectoryToS3 provides a mock function with given fields: localPath, bucket, prefix
func (_m *AWSer) UploadDirectoryToS3(localPath string, bucket string, prefix string) ([]string, []string) {
	ret := _m.Called(localPath, bucket, prefix)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string, string, string) []string); ok {
		r0 = rf(localPath, bucket, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 []string
	if rf, ok := ret.Get(1).(func(string, string, string) []string); ok {
		r1 = rf(localPath, bucket, prefix)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	return r0, r1
}
