// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigMasker is an autogenerated mock type for the ConfigMasker type
type ConfigMasker struct {
	mock.Mock
}

// Apply provides a mock function with given fields: arg, config, envvar, def
func (_m *ConfigMasker) Apply(arg string, config string, envvar string, def string) string {
	ret := _m.Called(arg, config, envvar, def)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(arg, config, envvar, def)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
