// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/Optum/dce-cli/pkg/service"
	mock "github.com/stretchr/testify/mock"
)

// Deployer is an autogenerated mock type for the Deployer type
type Deployer struct {
	mock.Mock
}

// Deploy provides a mock function with given fields: ctx, overrides
func (_m *Deployer) Deploy(ctx context.Context, overrides *service.DeployOverrides) error {
	ret := _m.Called(ctx, overrides)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.DeployOverrides) error); ok {
		r0 = rf(ctx, overrides)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostDeploy provides a mock function with given fields: ctx
func (_m *Deployer) PostDeploy(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
