// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/Optum/dce-cli/pkg/service"
	mock "github.com/stretchr/testify/mock"
)

// Deployer is an autogenerated mock type for the Deployer type
type Deployer struct {
	mock.Mock
}

// Deploy provides a mock function with given fields: ctx, overrides
func (_m *Deployer) Deploy(ctx context.Context, overrides *service.DeployOverrides) {
	_m.Called(ctx, overrides)
}
