// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Githuber is an autogenerated mock type for the Githuber type
type Githuber struct {
	mock.Mock
}

// DownloadGithubReleaseAsset provides a mock function with given fields: assetName
func (_m *Githuber) DownloadGithubReleaseAsset(assetName string) {
	_m.Called(assetName)
}
