// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Initer is an autogenerated mock type for the Initer type
type Initer struct {
	mock.Mock
}

// InitializeDCE provides a mock function with given fields:
func (_m *Initer) InitializeDCE() {
	_m.Called()
}
