// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Leaser is an autogenerated mock type for the Leaser type
type Leaser struct {
	mock.Mock
}

// CreateLease provides a mock function with given fields: principleID, budgetAmount, budgetCurrency, email
func (_m *Leaser) CreateLease(principleID string, budgetAmount float64, budgetCurrency string, email []string) {
	_m.Called(principleID, budgetAmount, budgetCurrency, email)
}

// EndLease provides a mock function with given fields: accountID, principleID
func (_m *Leaser) EndLease(accountID string, principleID string) {
	_m.Called(accountID, principleID)
}

// LoginToLease provides a mock function with given fields: loginAcctID, loginLeaseID, loginOpenBrowser
func (_m *Leaser) LoginToLease(loginAcctID string, loginLeaseID string, loginOpenBrowser bool) {
	_m.Called(loginAcctID, loginLeaseID, loginOpenBrowser)
}
