// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	service "github.com/Optum/dce-cli/pkg/service"
	mock "github.com/stretchr/testify/mock"
)

// Leaser is an autogenerated mock type for the Leaser type
type Leaser struct {
	mock.Mock
}

// CreateLease provides a mock function with given fields: principalID, budgetAmount, budgetCurrency, email, expiresOn
func (_m *Leaser) CreateLease(principalID string, budgetAmount float64, budgetCurrency string, email []string, expiresOn string) {
	_m.Called(principalID, budgetAmount, budgetCurrency, email, expiresOn)
}

// EndLease provides a mock function with given fields: accountID, principalID
func (_m *Leaser) EndLease(accountID string, principalID string) {
	_m.Called(accountID, principalID)
}

// GetLease provides a mock function with given fields: leaseID
func (_m *Leaser) GetLease(leaseID string) {
	_m.Called(leaseID)
}

// ListLeases provides a mock function with given fields: acctID, principalID, nextAcctID, nextPrincipalID, leaseStatus, pagLimit
func (_m *Leaser) ListLeases(acctID string, principalID string, nextAcctID string, nextPrincipalID string, leaseStatus string, pagLimit int64) {
	_m.Called(acctID, principalID, nextAcctID, nextPrincipalID, leaseStatus, pagLimit)
}

// Login provides a mock function with given fields: opts
func (_m *Leaser) Login(opts *service.LeaseLoginOptions) {
	_m.Called(opts)
}

// LoginByID provides a mock function with given fields: leaseID, opts
func (_m *Leaser) LoginByID(leaseID string, opts *service.LeaseLoginOptions) {
	_m.Called(leaseID, opts)
}
