// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Prompter is an autogenerated mock type for the Prompter type
type Prompter struct {
	mock.Mock
}

// PromptBasic provides a mock function with given fields: label, validator
func (_m *Prompter) PromptBasic(label string, validator func(string) error) *string {
	ret := _m.Called(label, validator)

	var r0 *string
	if rf, ok := ret.Get(0).(func(string, func(string) error) *string); ok {
		r0 = rf(label, validator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// PromptSelect provides a mock function with given fields: label, items
func (_m *Prompter) PromptSelect(label string, items []string) *string {
	ret := _m.Called(label, items)

	var r0 *string
	if rf, ok := ret.Get(0).(func(string, []string) *string); ok {
		r0 = rf(label, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}
