// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ResponseWithPayload is an autogenerated mock type for the ResponseWithPayload type
type ResponseWithPayload struct {
	mock.Mock
}

// GetPayload provides a mock function with given fields:
func (_m *ResponseWithPayload) GetPayload() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
