// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TerraformBinFileSystemUtil is an autogenerated mock type for the TerraformBinFileSystemUtil type
type TerraformBinFileSystemUtil struct {
	mock.Mock
}

// GetConfigDir provides a mock function with given fields:
func (_m *TerraformBinFileSystemUtil) GetConfigDir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsExistingFile provides a mock function with given fields: path
func (_m *TerraformBinFileSystemUtil) IsExistingFile(path string) bool {
	ret := _m.Called(path)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
