// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Terraformer is an autogenerated mock type for the Terraformer type
type Terraformer struct {
	mock.Mock
}

// Apply provides a mock function with given fields: ctx, tfVars
func (_m *Terraformer) Apply(ctx context.Context, tfVars []string) {
	_m.Called(ctx, tfVars)
}

// GetOutput provides a mock function with given fields: key
func (_m *Terraformer) GetOutput(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Init provides a mock function with given fields: args
func (_m *Terraformer) Init(args []string) {
	_m.Called(args)
}
