// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TerraformBinDownloader is an autogenerated mock type for the TerraformBinDownloader type
type TerraformBinDownloader struct {
	mock.Mock
}

// Download provides a mock function with given fields: url, localpath
func (_m *TerraformBinDownloader) Download(url string, localpath string) error {
	ret := _m.Called(url, localpath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(url, localpath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
