// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Usager is an autogenerated mock type for the Usager type
type Usager struct {
	mock.Mock
}

// GetUsage provides a mock function with given fields: startDate, endDate
func (_m *Usager) GetUsage(startDate float64, endDate float64) {
	_m.Called(startDate, endDate)
}
