// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Weber is an autogenerated mock type for the Weber type
type Weber struct {
	mock.Mock
}

// OpenURL provides a mock function with given fields: url
func (_m *Weber) OpenURL(url string) {
	_m.Called(url)
}
