// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsLeasesAuthParams creates a new OptionsLeasesAuthParams object
// with the default values initialized.
func NewOptionsLeasesAuthParams() *OptionsLeasesAuthParams {

	return &OptionsLeasesAuthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsLeasesAuthParamsWithTimeout creates a new OptionsLeasesAuthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsLeasesAuthParamsWithTimeout(timeout time.Duration) *OptionsLeasesAuthParams {

	return &OptionsLeasesAuthParams{

		timeout: timeout,
	}
}

// NewOptionsLeasesAuthParamsWithContext creates a new OptionsLeasesAuthParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsLeasesAuthParamsWithContext(ctx context.Context) *OptionsLeasesAuthParams {

	return &OptionsLeasesAuthParams{

		Context: ctx,
	}
}

// NewOptionsLeasesAuthParamsWithHTTPClient creates a new OptionsLeasesAuthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsLeasesAuthParamsWithHTTPClient(client *http.Client) *OptionsLeasesAuthParams {

	return &OptionsLeasesAuthParams{
		HTTPClient: client,
	}
}

/*OptionsLeasesAuthParams contains all the parameters to send to the API endpoint
for the options leases auth operation typically these are written to a http.Request
*/
type OptionsLeasesAuthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options leases auth params
func (o *OptionsLeasesAuthParams) WithTimeout(timeout time.Duration) *OptionsLeasesAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options leases auth params
func (o *OptionsLeasesAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options leases auth params
func (o *OptionsLeasesAuthParams) WithContext(ctx context.Context) *OptionsLeasesAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options leases auth params
func (o *OptionsLeasesAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options leases auth params
func (o *OptionsLeasesAuthParams) WithHTTPClient(client *http.Client) *OptionsLeasesAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options leases auth params
func (o *OptionsLeasesAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsLeasesAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
