// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsLeasesParams creates a new OptionsLeasesParams object
// with the default values initialized.
func NewOptionsLeasesParams() *OptionsLeasesParams {

	return &OptionsLeasesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsLeasesParamsWithTimeout creates a new OptionsLeasesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsLeasesParamsWithTimeout(timeout time.Duration) *OptionsLeasesParams {

	return &OptionsLeasesParams{

		timeout: timeout,
	}
}

// NewOptionsLeasesParamsWithContext creates a new OptionsLeasesParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsLeasesParamsWithContext(ctx context.Context) *OptionsLeasesParams {

	return &OptionsLeasesParams{

		Context: ctx,
	}
}

// NewOptionsLeasesParamsWithHTTPClient creates a new OptionsLeasesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsLeasesParamsWithHTTPClient(client *http.Client) *OptionsLeasesParams {

	return &OptionsLeasesParams{
		HTTPClient: client,
	}
}

/*OptionsLeasesParams contains all the parameters to send to the API endpoint
for the options leases operation typically these are written to a http.Request
*/
type OptionsLeasesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options leases params
func (o *OptionsLeasesParams) WithTimeout(timeout time.Duration) *OptionsLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options leases params
func (o *OptionsLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options leases params
func (o *OptionsLeasesParams) WithContext(ctx context.Context) *OptionsLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options leases params
func (o *OptionsLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options leases params
func (o *OptionsLeasesParams) WithHTTPClient(client *http.Client) *OptionsLeasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options leases params
func (o *OptionsLeasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
