// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsLeasesIDAuthParams creates a new OptionsLeasesIDAuthParams object
// with the default values initialized.
func NewOptionsLeasesIDAuthParams() *OptionsLeasesIDAuthParams {

	return &OptionsLeasesIDAuthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsLeasesIDAuthParamsWithTimeout creates a new OptionsLeasesIDAuthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsLeasesIDAuthParamsWithTimeout(timeout time.Duration) *OptionsLeasesIDAuthParams {

	return &OptionsLeasesIDAuthParams{

		timeout: timeout,
	}
}

// NewOptionsLeasesIDAuthParamsWithContext creates a new OptionsLeasesIDAuthParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsLeasesIDAuthParamsWithContext(ctx context.Context) *OptionsLeasesIDAuthParams {

	return &OptionsLeasesIDAuthParams{

		Context: ctx,
	}
}

// NewOptionsLeasesIDAuthParamsWithHTTPClient creates a new OptionsLeasesIDAuthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsLeasesIDAuthParamsWithHTTPClient(client *http.Client) *OptionsLeasesIDAuthParams {

	return &OptionsLeasesIDAuthParams{
		HTTPClient: client,
	}
}

/*OptionsLeasesIDAuthParams contains all the parameters to send to the API endpoint
for the options leases ID auth operation typically these are written to a http.Request
*/
type OptionsLeasesIDAuthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options leases ID auth params
func (o *OptionsLeasesIDAuthParams) WithTimeout(timeout time.Duration) *OptionsLeasesIDAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options leases ID auth params
func (o *OptionsLeasesIDAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options leases ID auth params
func (o *OptionsLeasesIDAuthParams) WithContext(ctx context.Context) *OptionsLeasesIDAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options leases ID auth params
func (o *OptionsLeasesIDAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options leases ID auth params
func (o *OptionsLeasesIDAuthParams) WithHTTPClient(client *http.Client) *OptionsLeasesIDAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options leases ID auth params
func (o *OptionsLeasesIDAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsLeasesIDAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
