// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsAccountsIDParams creates a new OptionsAccountsIDParams object
// with the default values initialized.
func NewOptionsAccountsIDParams() *OptionsAccountsIDParams {

	return &OptionsAccountsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsAccountsIDParamsWithTimeout creates a new OptionsAccountsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsAccountsIDParamsWithTimeout(timeout time.Duration) *OptionsAccountsIDParams {

	return &OptionsAccountsIDParams{

		timeout: timeout,
	}
}

// NewOptionsAccountsIDParamsWithContext creates a new OptionsAccountsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsAccountsIDParamsWithContext(ctx context.Context) *OptionsAccountsIDParams {

	return &OptionsAccountsIDParams{

		Context: ctx,
	}
}

// NewOptionsAccountsIDParamsWithHTTPClient creates a new OptionsAccountsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsAccountsIDParamsWithHTTPClient(client *http.Client) *OptionsAccountsIDParams {

	return &OptionsAccountsIDParams{
		HTTPClient: client,
	}
}

/*OptionsAccountsIDParams contains all the parameters to send to the API endpoint
for the options accounts ID operation typically these are written to a http.Request
*/
type OptionsAccountsIDParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options accounts ID params
func (o *OptionsAccountsIDParams) WithTimeout(timeout time.Duration) *OptionsAccountsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options accounts ID params
func (o *OptionsAccountsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options accounts ID params
func (o *OptionsAccountsIDParams) WithContext(ctx context.Context) *OptionsAccountsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options accounts ID params
func (o *OptionsAccountsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options accounts ID params
func (o *OptionsAccountsIDParams) WithHTTPClient(client *http.Client) *OptionsAccountsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options accounts ID params
func (o *OptionsAccountsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsAccountsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
