// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsAuthParams creates a new OptionsAuthParams object
// with the default values initialized.
func NewOptionsAuthParams() *OptionsAuthParams {

	return &OptionsAuthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsAuthParamsWithTimeout creates a new OptionsAuthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsAuthParamsWithTimeout(timeout time.Duration) *OptionsAuthParams {

	return &OptionsAuthParams{

		timeout: timeout,
	}
}

// NewOptionsAuthParamsWithContext creates a new OptionsAuthParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsAuthParamsWithContext(ctx context.Context) *OptionsAuthParams {

	return &OptionsAuthParams{

		Context: ctx,
	}
}

// NewOptionsAuthParamsWithHTTPClient creates a new OptionsAuthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsAuthParamsWithHTTPClient(client *http.Client) *OptionsAuthParams {

	return &OptionsAuthParams{
		HTTPClient: client,
	}
}

/*OptionsAuthParams contains all the parameters to send to the API endpoint
for the options auth operation typically these are written to a http.Request
*/
type OptionsAuthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options auth params
func (o *OptionsAuthParams) WithTimeout(timeout time.Duration) *OptionsAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options auth params
func (o *OptionsAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options auth params
func (o *OptionsAuthParams) WithContext(ctx context.Context) *OptionsAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options auth params
func (o *OptionsAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options auth params
func (o *OptionsAuthParams) WithHTTPClient(client *http.Client) *OptionsAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options auth params
func (o *OptionsAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
