// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteLeasesParams creates a new DeleteLeasesParams object
// with the default values initialized.
func NewDeleteLeasesParams() *DeleteLeasesParams {
	var ()
	return &DeleteLeasesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLeasesParamsWithTimeout creates a new DeleteLeasesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLeasesParamsWithTimeout(timeout time.Duration) *DeleteLeasesParams {
	var ()
	return &DeleteLeasesParams{

		timeout: timeout,
	}
}

// NewDeleteLeasesParamsWithContext creates a new DeleteLeasesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLeasesParamsWithContext(ctx context.Context) *DeleteLeasesParams {
	var ()
	return &DeleteLeasesParams{

		Context: ctx,
	}
}

// NewDeleteLeasesParamsWithHTTPClient creates a new DeleteLeasesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLeasesParamsWithHTTPClient(client *http.Client) *DeleteLeasesParams {
	var ()
	return &DeleteLeasesParams{
		HTTPClient: client,
	}
}

/*DeleteLeasesParams contains all the parameters to send to the API endpoint
for the delete leases operation typically these are written to a http.Request
*/
type DeleteLeasesParams struct {

	/*Lease
	  The owner of the lease

	*/
	Lease DeleteLeasesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete leases params
func (o *DeleteLeasesParams) WithTimeout(timeout time.Duration) *DeleteLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete leases params
func (o *DeleteLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete leases params
func (o *DeleteLeasesParams) WithContext(ctx context.Context) *DeleteLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete leases params
func (o *DeleteLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete leases params
func (o *DeleteLeasesParams) WithHTTPClient(client *http.Client) *DeleteLeasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete leases params
func (o *DeleteLeasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLease adds the lease to the delete leases params
func (o *DeleteLeasesParams) WithLease(lease DeleteLeasesBody) *DeleteLeasesParams {
	o.SetLease(lease)
	return o
}

// SetLease adds the lease to the delete leases params
func (o *DeleteLeasesParams) SetLease(lease DeleteLeasesBody) {
	o.Lease = lease
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Lease); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
