// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAccountsIDParams creates a new DeleteAccountsIDParams object
// with the default values initialized.
func NewDeleteAccountsIDParams() *DeleteAccountsIDParams {
	var ()
	return &DeleteAccountsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAccountsIDParamsWithTimeout creates a new DeleteAccountsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAccountsIDParamsWithTimeout(timeout time.Duration) *DeleteAccountsIDParams {
	var ()
	return &DeleteAccountsIDParams{

		timeout: timeout,
	}
}

// NewDeleteAccountsIDParamsWithContext creates a new DeleteAccountsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAccountsIDParamsWithContext(ctx context.Context) *DeleteAccountsIDParams {
	var ()
	return &DeleteAccountsIDParams{

		Context: ctx,
	}
}

// NewDeleteAccountsIDParamsWithHTTPClient creates a new DeleteAccountsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAccountsIDParamsWithHTTPClient(client *http.Client) *DeleteAccountsIDParams {
	var ()
	return &DeleteAccountsIDParams{
		HTTPClient: client,
	}
}

/*DeleteAccountsIDParams contains all the parameters to send to the API endpoint
for the delete accounts ID operation typically these are written to a http.Request
*/
type DeleteAccountsIDParams struct {

	/*ID
	  The ID of the account to be deleted.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete accounts ID params
func (o *DeleteAccountsIDParams) WithTimeout(timeout time.Duration) *DeleteAccountsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete accounts ID params
func (o *DeleteAccountsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete accounts ID params
func (o *DeleteAccountsIDParams) WithContext(ctx context.Context) *DeleteAccountsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete accounts ID params
func (o *DeleteAccountsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete accounts ID params
func (o *DeleteAccountsIDParams) WithHTTPClient(client *http.Client) *DeleteAccountsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete accounts ID params
func (o *DeleteAccountsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete accounts ID params
func (o *DeleteAccountsIDParams) WithID(id string) *DeleteAccountsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete accounts ID params
func (o *DeleteAccountsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAccountsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
