// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAccountsReader is a Reader for the GetAccounts structure.
type GetAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAccountsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAccountsOK creates a GetAccountsOK with default headers values
func NewGetAccountsOK() *GetAccountsOK {
	return &GetAccountsOK{}
}

/*GetAccountsOK handles this case with default header values.

A list of accounts
*/
type GetAccountsOK struct {
	AccessControlAllowHeaders string

	AccessControlAllowMethods string

	AccessControlAllowOrigin string

	Payload []*GetAccountsOKBodyItems0
}

func (o *GetAccountsOK) Error() string {
	return fmt.Sprintf("[GET /accounts][%d] getAccountsOK  %+v", 200, o.Payload)
}

func (o *GetAccountsOK) GetPayload() []*GetAccountsOKBodyItems0 {
	return o.Payload
}

func (o *GetAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Access-Control-Allow-Headers
	o.AccessControlAllowHeaders = response.GetHeader("Access-Control-Allow-Headers")

	// response header Access-Control-Allow-Methods
	o.AccessControlAllowMethods = response.GetHeader("Access-Control-Allow-Methods")

	// response header Access-Control-Allow-Origin
	o.AccessControlAllowOrigin = response.GetHeader("Access-Control-Allow-Origin")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountsForbidden creates a GetAccountsForbidden with default headers values
func NewGetAccountsForbidden() *GetAccountsForbidden {
	return &GetAccountsForbidden{}
}

/*GetAccountsForbidden handles this case with default header values.

Unauthorized
*/
type GetAccountsForbidden struct {
}

func (o *GetAccountsForbidden) Error() string {
	return fmt.Sprintf("[GET /accounts][%d] getAccountsForbidden ", 403)
}

func (o *GetAccountsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetAccountsOKBodyItems0 Account Details
swagger:model GetAccountsOKBodyItems0
*/
type GetAccountsOKBodyItems0 struct {

	// Status of the Account.
	// "Ready": The account is clean and ready for lease
	// "NotReady": The account is in "dirty" state, and needs to be reset before it may be leased.
	// "Leased": The account is leased to a principal
	//
	// Enum: [Ready NotReady Leased]
	AccountStatus string `json:"accountStatus,omitempty"`

	// ARN for an IAM role within this AWS account. The Redbox master account will assume this IAM role to execute operations within this AWS account. This IAM role is configured by the client, and must be configured with [a Trust Relationship with the Redbox master account.](/https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html)
	AdminRoleArn string `json:"adminRoleArn,omitempty"`

	// Epoch timestamp, when account record was created
	CreatedOn int64 `json:"createdOn,omitempty"`

	// AWS Account ID
	ID string `json:"id,omitempty"`

	// Epoch timestamp, when account record was last modified
	LastModifiedOn int64 `json:"lastModifiedOn,omitempty"`

	// Any organization specific data pertaining to the account that needs to be persisted
	Metadata interface{} `json:"metadata,omitempty"`

	// The S3 object ETag used to apply the Principal IAM Policy within this AWS account.  This policy is created by the Redbox master account, and is assumed by people with access to principalRoleArn.
	PrincipalPolicyHash string `json:"principalPolicyHash,omitempty"`

	// ARN for an IAM role within this AWS account. This role is created by the Redbox master account, and may be assumed by principals to login to their AWS Redbox account.
	PrincipalRoleArn string `json:"principalRoleArn,omitempty"`
}

// Validate validates this get accounts o k body items0
func (o *GetAccountsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAccountStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getAccountsOKBodyItems0TypeAccountStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Ready","NotReady","Leased"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getAccountsOKBodyItems0TypeAccountStatusPropEnum = append(getAccountsOKBodyItems0TypeAccountStatusPropEnum, v)
	}
}

const (

	// GetAccountsOKBodyItems0AccountStatusReady captures enum value "Ready"
	GetAccountsOKBodyItems0AccountStatusReady string = "Ready"

	// GetAccountsOKBodyItems0AccountStatusNotReady captures enum value "NotReady"
	GetAccountsOKBodyItems0AccountStatusNotReady string = "NotReady"

	// GetAccountsOKBodyItems0AccountStatusLeased captures enum value "Leased"
	GetAccountsOKBodyItems0AccountStatusLeased string = "Leased"
)

// prop value enum
func (o *GetAccountsOKBodyItems0) validateAccountStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, getAccountsOKBodyItems0TypeAccountStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (o *GetAccountsOKBodyItems0) validateAccountStatus(formats strfmt.Registry) error {

	if swag.IsZero(o.AccountStatus) { // not required
		return nil
	}

	// value enum
	if err := o.validateAccountStatusEnum("accountStatus", "body", o.AccountStatus); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAccountsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAccountsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetAccountsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
