// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuthFileParams creates a new GetAuthFileParams object
// with the default values initialized.
func NewGetAuthFileParams() *GetAuthFileParams {

	return &GetAuthFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthFileParamsWithTimeout creates a new GetAuthFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthFileParamsWithTimeout(timeout time.Duration) *GetAuthFileParams {

	return &GetAuthFileParams{

		timeout: timeout,
	}
}

// NewGetAuthFileParamsWithContext creates a new GetAuthFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthFileParamsWithContext(ctx context.Context) *GetAuthFileParams {

	return &GetAuthFileParams{

		Context: ctx,
	}
}

// NewGetAuthFileParamsWithHTTPClient creates a new GetAuthFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthFileParamsWithHTTPClient(client *http.Client) *GetAuthFileParams {

	return &GetAuthFileParams{
		HTTPClient: client,
	}
}

/*GetAuthFileParams contains all the parameters to send to the API endpoint
for the get auth file operation typically these are written to a http.Request
*/
type GetAuthFileParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth file params
func (o *GetAuthFileParams) WithTimeout(timeout time.Duration) *GetAuthFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth file params
func (o *GetAuthFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth file params
func (o *GetAuthFileParams) WithContext(ctx context.Context) *GetAuthFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth file params
func (o *GetAuthFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth file params
func (o *GetAuthFileParams) WithHTTPClient(client *http.Client) *GetAuthFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth file params
func (o *GetAuthFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
