// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAccountsIDReader is a Reader for the GetAccountsID structure.
type GetAccountsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAccountsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAccountsIDOK creates a GetAccountsIDOK with default headers values
func NewGetAccountsIDOK() *GetAccountsIDOK {
	return &GetAccountsIDOK{}
}

/*GetAccountsIDOK handles this case with default header values.

Account Details
*/
type GetAccountsIDOK struct {
	AccessControlAllowHeaders string

	AccessControlAllowMethods string

	AccessControlAllowOrigin string
}

func (o *GetAccountsIDOK) Error() string {
	return fmt.Sprintf("[GET /accounts/{id}][%d] getAccountsIdOK ", 200)
}

func (o *GetAccountsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Access-Control-Allow-Headers
	o.AccessControlAllowHeaders = response.GetHeader("Access-Control-Allow-Headers")

	// response header Access-Control-Allow-Methods
	o.AccessControlAllowMethods = response.GetHeader("Access-Control-Allow-Methods")

	// response header Access-Control-Allow-Origin
	o.AccessControlAllowOrigin = response.GetHeader("Access-Control-Allow-Origin")

	return nil
}

// NewGetAccountsIDForbidden creates a GetAccountsIDForbidden with default headers values
func NewGetAccountsIDForbidden() *GetAccountsIDForbidden {
	return &GetAccountsIDForbidden{}
}

/*GetAccountsIDForbidden handles this case with default header values.

Failed to retrieve account
*/
type GetAccountsIDForbidden struct {
}

func (o *GetAccountsIDForbidden) Error() string {
	return fmt.Sprintf("[GET /accounts/{id}][%d] getAccountsIdForbidden ", 403)
}

func (o *GetAccountsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
