// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetLeasesIDReader is a Reader for the GetLeasesID structure.
type GetLeasesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLeasesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLeasesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetLeasesIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLeasesIDOK creates a GetLeasesIDOK with default headers values
func NewGetLeasesIDOK() *GetLeasesIDOK {
	return &GetLeasesIDOK{}
}

/*GetLeasesIDOK handles this case with default header values.

Lease Details
*/
type GetLeasesIDOK struct {
	AccessControlAllowHeaders string

	AccessControlAllowMethods string

	AccessControlAllowOrigin string
}

func (o *GetLeasesIDOK) Error() string {
	return fmt.Sprintf("[GET /leases/{id}][%d] getLeasesIdOK ", 200)
}

func (o *GetLeasesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Access-Control-Allow-Headers
	o.AccessControlAllowHeaders = response.GetHeader("Access-Control-Allow-Headers")

	// response header Access-Control-Allow-Methods
	o.AccessControlAllowMethods = response.GetHeader("Access-Control-Allow-Methods")

	// response header Access-Control-Allow-Origin
	o.AccessControlAllowOrigin = response.GetHeader("Access-Control-Allow-Origin")

	return nil
}

// NewGetLeasesIDForbidden creates a GetLeasesIDForbidden with default headers values
func NewGetLeasesIDForbidden() *GetLeasesIDForbidden {
	return &GetLeasesIDForbidden{}
}

/*GetLeasesIDForbidden handles this case with default header values.

Failed to retrieve lease
*/
type GetLeasesIDForbidden struct {
}

func (o *GetLeasesIDForbidden) Error() string {
	return fmt.Sprintf("[GET /leases/{id}][%d] getLeasesIdForbidden ", 403)
}

func (o *GetLeasesIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
