// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuthParams creates a new GetAuthParams object
// with the default values initialized.
func NewGetAuthParams() *GetAuthParams {

	return &GetAuthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthParamsWithTimeout creates a new GetAuthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthParamsWithTimeout(timeout time.Duration) *GetAuthParams {

	return &GetAuthParams{

		timeout: timeout,
	}
}

// NewGetAuthParamsWithContext creates a new GetAuthParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthParamsWithContext(ctx context.Context) *GetAuthParams {

	return &GetAuthParams{

		Context: ctx,
	}
}

// NewGetAuthParamsWithHTTPClient creates a new GetAuthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthParamsWithHTTPClient(client *http.Client) *GetAuthParams {

	return &GetAuthParams{
		HTTPClient: client,
	}
}

/*GetAuthParams contains all the parameters to send to the API endpoint
for the get auth operation typically these are written to a http.Request
*/
type GetAuthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth params
func (o *GetAuthParams) WithTimeout(timeout time.Duration) *GetAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth params
func (o *GetAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth params
func (o *GetAuthParams) WithContext(ctx context.Context) *GetAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth params
func (o *GetAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth params
func (o *GetAuthParams) WithHTTPClient(client *http.Client) *GetAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth params
func (o *GetAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
