// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostLeasesParams creates a new PostLeasesParams object
// with the default values initialized.
func NewPostLeasesParams() *PostLeasesParams {
	var ()
	return &PostLeasesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLeasesParamsWithTimeout creates a new PostLeasesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLeasesParamsWithTimeout(timeout time.Duration) *PostLeasesParams {
	var ()
	return &PostLeasesParams{

		timeout: timeout,
	}
}

// NewPostLeasesParamsWithContext creates a new PostLeasesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLeasesParamsWithContext(ctx context.Context) *PostLeasesParams {
	var ()
	return &PostLeasesParams{

		Context: ctx,
	}
}

// NewPostLeasesParamsWithHTTPClient creates a new PostLeasesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLeasesParamsWithHTTPClient(client *http.Client) *PostLeasesParams {
	var ()
	return &PostLeasesParams{
		HTTPClient: client,
	}
}

/*PostLeasesParams contains all the parameters to send to the API endpoint
for the post leases operation typically these are written to a http.Request
*/
type PostLeasesParams struct {

	/*Lease
	  The owner of the lease

	*/
	Lease PostLeasesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post leases params
func (o *PostLeasesParams) WithTimeout(timeout time.Duration) *PostLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post leases params
func (o *PostLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post leases params
func (o *PostLeasesParams) WithContext(ctx context.Context) *PostLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post leases params
func (o *PostLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post leases params
func (o *PostLeasesParams) WithHTTPClient(client *http.Client) *PostLeasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post leases params
func (o *PostLeasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLease adds the lease to the post leases params
func (o *PostLeasesParams) WithLease(lease PostLeasesBody) *PostLeasesParams {
	o.SetLease(lease)
	return o
}

// SetLease adds the lease to the post leases params
func (o *PostLeasesParams) SetLease(lease PostLeasesBody) {
	o.Lease = lease
}

// WriteToRequest writes these params to a swagger request
func (o *PostLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Lease); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
