// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// LeaseStatus Status of the Lease.
// "Active": The principal is leased and has access to the account
// "Decommissioned": The principal was previously leased to the account, but now is not.
// "FinanceLock": The principal is leased to the account, but has hit a budget threshold, and is locked out of the account.
// "ResetLock": The principal is leased to the account, but the account is being reset. The principal's access is temporarily revoked, and will be given back after the reset process is complete.
// "ResetFinanceLock": The principal is leased to the account, but has been locked out for hitting a budget threshold. Additionally, the account is being reset. After reset, the principal's access will _not_ be restored, and the LeaseStatus will be set back to `ResetLock`.
//
// swagger:model leaseStatus
type LeaseStatus string

const (

	// LeaseStatusActive captures enum value "Active"
	LeaseStatusActive LeaseStatus = "Active"

	// LeaseStatusDecommissioned captures enum value "Decommissioned"
	LeaseStatusDecommissioned LeaseStatus = "Decommissioned"

	// LeaseStatusFinanceLock captures enum value "FinanceLock"
	LeaseStatusFinanceLock LeaseStatus = "FinanceLock"

	// LeaseStatusResetLock captures enum value "ResetLock"
	LeaseStatusResetLock LeaseStatus = "ResetLock"

	// LeaseStatusResetFinanceLock captures enum value "ResetFinanceLock"
	LeaseStatusResetFinanceLock LeaseStatus = "ResetFinanceLock"
)

// for schema
var leaseStatusEnum []interface{}

func init() {
	var res []LeaseStatus
	if err := json.Unmarshal([]byte(`["Active","Decommissioned","FinanceLock","ResetLock","ResetFinanceLock"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		leaseStatusEnum = append(leaseStatusEnum, v)
	}
}

func (m LeaseStatus) validateLeaseStatusEnum(path, location string, value LeaseStatus) error {
	if err := validate.Enum(path, location, value, leaseStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this lease status
func (m LeaseStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateLeaseStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
