// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LeaseAuth Lease Authentication
// swagger:model leaseAuth
type LeaseAuth struct {

	// Access Key ID for access to the AWS API
	AccessKeyID string `json:"accessKeyId,omitempty"`

	// URL to access the AWS Console
	ConsoleURL string `json:"consoleUrl,omitempty"`

	// Secret Access Key for access to the AWS API
	SecretAccessKey string `json:"secretAccessKey,omitempty"`

	// Session Token for access to the AWS API
	SessionToken string `json:"sessionToken,omitempty"`
}

// Validate validates this lease auth
func (m *LeaseAuth) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LeaseAuth) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LeaseAuth) UnmarshalBinary(b []byte) error {
	var res LeaseAuth
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
